[project]
name = "ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "debugpy>=1.8.16",
    "fastapi[standard]>=0.116.1",
    "httpx>=0.28.1",
    "litellm>=1.76.1",
]
